name: pmmp_example_code
description: web site contains tips for pmmp users

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  markdown: ^4.0.0

dev_dependencies:
  pedantic: ^1.10.0
