name: setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: convert markdown files to html and generate data files
        env:
          KEY: ${{ secrets.KEY }}
        run: dart bin/main.dart

      - run: git checkout gh-pages
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'web'
          author_name: suinua
          branch: gh-pages
          committer_name: suinua