name: setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: convert markdown files to html and generate data files
        env:
          PATH: ${{ GITHUB_ACTION_PATH }}
          KEY: ${{ secrets.KEY }}
        run: dart bin/main.dart
